### ISSUE TITLE
Peer review 

### ISSUE THREAD

**Issue by mbergevoet** [lars-ruijs/frontend-data#1]
## repo
* In je gitignore staat nog weinig, misschien heb hier genoeg aan maar voeg nog dingen toe als `*.csv` `*.json`
* Duidelijke concept beschrijving, deelvragen, variabelen uit de datasets, schetsen en functional patterns
* Goed dat je aangeeft wat je doet met lege velden
* Goed dat de bronnen onderaan de README staan
* Voeg nog een link naar je visualisatie toe in je README

## wiki
* Maak nog een pagina aan voor het transformeren en opschonen van de data van de RDW
* Documenteer je update pattern daar ook in
* Voor wat er al in de wiki staat is duidelijk wat je hebt geleerd

## code
* Nette commets in je code die beschrijven wat alles doet

**Comment by lars-ruijs** [comment]
- [X] link naar visualisatie toegevoegd
- [X] pagina voor transformeren en opschonen RDW data aangemaakt
- [X] het maken van de visualisatie met D3 en het update pattern zijn gedocumenteerd.
